url: https://www.joshdeveloper.me   # with the https protocol
enforce_ssl: www.joshdeveloper.me   # without any protocol

gems:
  - jekyll-seo-tag
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed